In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df = pd.read_csv('spam.csv')

In [3]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
c = df.columns.tolist()
c

['Category', 'Message']

In [6]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [7]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [9]:
X_train.shape

(4457,)

In [10]:
type(X_train.values)

numpy.ndarray

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
v = CountVectorizer()

In [15]:
X_train_cv = v.fit_transform(X_train.values)

In [17]:
X_train_cv

<4457x7818 sparse matrix of type '<class 'numpy.int64'>'
	with 59190 stored elements in Compressed Sparse Row format>

In [18]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
X_train_cv.shape

# there are 7818 vocabularies(words) each email is a vector of size 7818

(4457, 7818)

In [37]:
v.get_feature_names_out()[56]

'0808'

In [29]:
v.vocabulary_

{'you': 7777,
 'are': 1072,
 'awarded': 1196,
 'sipix': 6256,
 'digital': 2345,
 'camera': 1653,
 'call': 1632,
 '09061221061': 185,
 'from': 3050,
 'landline': 4045,
 'delivery': 2268,
 'within': 7617,
 '28days': 380,
 'cs': 2117,
 'box177': 1484,
 'm221bp': 4325,
 '2yr': 429,
 'warranty': 7460,
 '150ppm': 309,
 '16': 315,
 '99': 753,
 'hey': 3450,
 'can': 1657,
 'tell': 6820,
 'me': 4463,
 'blake': 1403,
 'address': 836,
 'carlos': 1693,
 'wanted': 7451,
 'to': 7007,
 'meet': 4480,
 'him': 3463,
 'there': 6901,
 'but': 1601,
 'got': 3230,
 'lost': 4260,
 'and': 986,
 'he': 3396,
 'not': 4881,
 'answering': 1010,
 'his': 3470,
 'phone': 5247,
 'ready': 5665,
 'then': 6895,
 'yup': 7800,
 'no': 4848,
 'need': 4783,
 'll': 4206,
 'jus': 3909,
 'wait': 7427,
 'rain': 5614,
 'stop': 6568,
 'get': 3147,
 'put': 5573,
 'on': 4990,
 'your': 7782,
 'excellent': 2722,
 'sub': 6623,
 'face': 2769,
 'leave': 4101,
 'it': 3791,
 'big': 1376,
 'deal': 2218,
 'take': 6756,
 'care': 1681,
 'ok': 497

In [41]:
X_train_np = X_train_cv.toarray()

In [44]:
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [45]:
#first e-mail
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [47]:
# to find the words in the first email
np.where(X_train_np[0]!=0)

(array([ 185,  309,  315,  380,  429,  753, 1072, 1196, 1484, 1632, 1653,
        2117, 2268, 2345, 3050, 4045, 4325, 6256, 7460, 7617, 7777],
       dtype=int64),)

In [50]:
#we can access words in first email from the above indices where it is 1
v.get_feature_names_out()[380]

'28days'

In [53]:
X_train[:4][5524]

'You are awarded a SiPix Digital Camera! call 09061221061 from landline. Delivery within 28days. T Cs Box177. M221BP. 2yr warranty. 150ppm. 16 . p p£3.99'

In [57]:
X_train_np[0][4045]

1

In [59]:
v.get_feature_names_out()[1196]

'awarded'

In [60]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [61]:
X_test_cv = v.transform(X_test)

In [65]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)

In [67]:
print(classification_report(y_test,y_pred))
      

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       962
           1       0.98      0.92      0.95       153

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [82]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    
    
]
emails_cv = v.transform(emails)
model.predict(emails_cv)

array([0, 1], dtype=int64)

In [83]:
from sklearn.pipeline import Pipeline

In [85]:
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
    ])

In [86]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [90]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       962
           1       0.98      0.92      0.95       153

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

